-- Migration: V1 - Criação da tabela de beneficiários
-- Padrão da disciplina: chaves primárias com prefixo 'id_'

CREATE TABLE beneficiarios (
    id_beneficiario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                     VARCHAR(150) NOT NULL,
    cpf                      VARCHAR(14)  NOT NULL UNIQUE,
    telefone                 VARCHAR(20),
    endereco                 VARCHAR(255),
    situacao_vulnerabilidade VARCHAR(500),
    data_cadastro            DATE         NOT NULL
);

-- Índice para otimizar buscas por CPF
CREATE INDEX idx_beneficiarios_cpf ON beneficiarios(cpf);
