-- Migration: V2 - Criação da tabela de doadores
-- Padrão da disciplina: chaves primárias com prefixo 'id_'

CREATE TABLE doadores (
    id_doador BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(150) NOT NULL,
    tipo      VARCHAR(20)  NOT NULL,
    email     VARCHAR(150),
    telefone  VARCHAR(20),
    CONSTRAINT ck_doadores_tipo CHECK (tipo IN ('PESSOA_FISICA', 'PESSOA_JURIDICA'))
);

CREATE INDEX idx_doadores_email ON doadores(email);
