-- Migration: V3 - Criação da tabela de doações
-- Padrão da disciplina: chaves primárias com prefixo 'id_'

CREATE TABLE doacoes (
    id_doacao   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_doador   BIGINT        NOT NULL,
    data_doacao DATE          NOT NULL,
    valor       DECIMAL(10,2),
    tipo        VARCHAR(20)   NOT NULL,
    descricao   VARCHAR(500),
    CONSTRAINT fk_doacao_doador
        FOREIGN KEY (id_doador) REFERENCES doadores(id_doador)
);

CREATE INDEX idx_doacoes_data ON doacoes(data_doacao);
CREATE INDEX idx_doacoes_tipo ON doacoes(tipo);