CREATE TABLE produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR(150) NOT NULL UNIQUE,
    categoria_produto VARCHAR(20) NOT NULL,
    estoque_atual INT NOT NULL,
    estoque_minimo INT NOT NULL,
    unidade_medida VARCHAR(20) NOT NULL,
    data_cadastro DATE NOT NULL
);

CREATE INDEX idx_produto_nome ON produtos(nome_produto);
CREATE INDEX idx_produto_categoria ON produtos(categoria_produto);